### ISSUE TITLE
kustomization CRD for BaaS

### ISSUE THREAD

**Issue by BorntraegerMarc** [appuio/docs#73]
I know this issue doesn't belong in this repository but I didn't find any better place for it. If you could point me in the right one I'd also appreciate it 🙂 

The docs currently mention the [Backup as a Service](https://docs.appuio.ch/en/latest/baas.html) with restic.

Is there any intend to publish an open source kustomization [CRD](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#crds)? It would be especially useful when having multiple S3 buckets so that I could define a variable per OCP project with the correct bucket name in it.

Currently I need to overwrite the whole object in every project:
```
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: backup-pods
spec:
  backend:
    s3:
      bucket: XXX
```
